dist: trusty

language: php

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer install --prefer-dist

script:
  - make qa
  - if [[ $TRAVIS_BRANCH = master ]]; then make full-tests; else make unit-tests; fi

after_success:
  bash <(curl -s https://codecov.io/bash)
